services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - LONGPORT_APP_KEY=${LONGPORT_APP_KEY}
      - LONGPORT_APP_SECRET=${LONGPORT_APP_SECRET}
      - LONGPORT_ACCESS_TOKEN=${LONGPORT_ACCESS_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
