services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3000"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
