version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - LONGBRIDGE_APP_KEY=${LONGBRIDGE_APP_KEY}
      - LONGBRIDGE_APP_SECRET=${LONGBRIDGE_APP_SECRET}
      - LONGBRIDGE_ACCESS_TOKEN=${LONGBRIDGE_ACCESS_TOKEN}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
